### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by norbs57**
Added example: zebra puzzle

### CODE REVIEW

**Review by gnboorse — CHANGES_REQUESTED** [review]
I LOVE THIS! 

Great work. The only issue I see with this PR is the files you added are in the root directory, not in `examples/`. 

If you move the files into that directory, I will gladly accept and merge the PR!

**Review by gnboorse — APPROVED** [review]
thanks for making the changes.

**Comment by gnboorse** [comment]
@norbs57 did you mean to close this?

**Comment by norbs57** [comment]
Apologies for putting the files in the wrong folder. It was my first ever Github Pull request and I don't use Github on my local machine. 

Thanks for your CSP package, it mak

**Comment by norbs57** [comment]
Sorry, I am new to Github Pull requests - it is my first one. I have not quite understood all the mechanisms :)

**Comment by norbs57** [comment]
Thanks for your CSP package - it made coding up the Zebra example very easy. 
Apologies for putting files into the wrong folder. I don't actually use Github on my local machine, I guess I should.

**Comment by gnboorse** [comment]
No worries @norbs57.

Thanks for making your pull request and appreciating the library. I have gone ahead and merged it for you!

**Comment by norbs57** [comment]
Hi Gabriel,



Thanks for the Github publication of your CSP implementation in Golang.



Please feel free to do whatever you like with my Zebra puzzle code. I was
just trying to “give something” back.



It is my first ever “Github pull request”. Apologies for putting the files
into the wrong folder.



I will try to solve a Kattis problem using your system
https://open.kattis.com/problems/amiga.

I  may be able to give you more feedback on your CSP implementation after
that.



All the best,

Norbert











*From:* Gabriel Boorse ***@***.***
*Sent:* 23 March 2021 00:12
*To:* gnboorse/centipede ***@***.***>
*Cc:* Norbs ***@***.***>; Author ***@***.***>
*Subject:* Re: [gnboorse/centipede] Add files via upload (#3)



***@***.**** requested changes on this pull request.

I LOVE THIS!

Great work. The only issue I see with this PR is the files you added are in
the root directory, not in examples/.

If you move the files into that directory, I will gladly accept and merge
the PR!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gnboorse/centipede/pull/3#pullrequestreview-618078206>,
or unsubscribe

**Pull request merged**
